site_name: Lumos文档
nav:
  - 简介: index.md
  - 安装: index.md
  - 快速入门: index.md
  - API参考: index.md
  - 经典案例: index.md
  - 深度学习: index.md
  - 版本: index.md
  - 其他: index.md

theme: readthedocs

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','js/mathjaxhelper.js']
