site_name: Lumos文档
nav:
  - 简介: index.md
  - 安装: 安装/index.md
  - 快速入门: 快速入门/index.md
  - API参考:
    - 会话构建: API参考/会话构建.md
    - 模型构建: API参考/模型构建.md
    - 其他: API参考/其他.md
  - 经典案例:
    - 经典案例/xor.md
    - 经典案例/lenet5.md
    - 经典案例/alexnet.md
    - 经典案例/vgg16.md
  - 深度学习:
    - 深度学习/全连接神经网络.md
    - 深度学习/卷积.md
    - 深度学习/池化.md
    - 深度学习/激活函数.md
    - 深度学习/损失函数.md
    - 深度学习/批次归一化.md
    - 深度学习/权重初始化.md
    - 深度学习/参数优化器.md
    - 深度学习/dropout.md
  - 版本:
    - 版本/v1.md
  - 其他:
    - 其他/index.md

theme: readthedocs

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','js/mathjaxhelper.js']
